### PR TITLE
Make make_scratch_buffer make a scratch buffer

### PR DESCRIPTION
**Pull request by dceluis**
I find that this allows for a more natural exit of the debug buffer, in my case leader-q was already mapped to exit buffer, and users might have similar mappings, but even :q works fine, as seen below:

before:
noscratch

after
scratch

nvim docs
image

### CODE REVIEW

**Comment by chottolabs** [comment]
yeah honestly i agree w/ this change - i originally added it because i thought i would want leave the buffer open and look for it later with telescope, but i rarely ever ended up doing that

should get rid of the keymap too?

**Comment by chottolabs** [comment]
> :q works fine

I'd say my intended usage would be `:bd` to return to the buffer i was on before

**Comment by dceluis** [comment]
> yeah honestly i agree w/ this change - i originally added it because i thought i would want leave the buffer open and look for it later with telescope, but i rarely ever ended up doing that

one could always save the buffer to work with it later i suppose

> should get rid of the keymap too?

would it be possible to define a buffer-local autocmd so the user could define a shortcut if needed? (I have actually set "q" as my shortcut)
docs make it seem like it would, I can try adding that to this PR if you think it'd be a good idea.
image

**Comment by dceluis** [comment]
now that I think of it.. that would mean defining a global keymap, without a reference to the scratch buffer so I don't think that would work at all

**Comment by chottolabs** [comment]
> that would mean defining a global keymap, without a reference to the scratch buffer so I don't think that would work at all

I was just about to say that sounds like a good idea lol

---

not sure if there's a more elegant way to do it, but need to add something like this to wipe the value (when doing `:bd`)

`presets.lua`
```
  local bufnr = kznllm.make_scratch_buffer()
  M.BUFFER_STATE.SCRATCH = bufnr

  api.nvim_buf_attach(bufnr, false, {
    on_detach = function()
      if bufnr == M.BUFFER_STATE.SCRATCH then
        M.BUFFER_STATE.SCRATCH = nil
      end
    end,
  })
```

**Comment by dceluis** [comment]
<s>
i think there might be a shorter way, on buffer creation:
`vim.bo[buf].bufhidden = 'wipe'     -- Automatically remove the buffer when closed`

(default is `hide`, https://neovim.io/doc/user/windows.html#scratch-buffer)
</s>

**Comment by dceluis** [comment]
Sorry, you meant the global variable.
What about creating the buffer with a variable, like, `vim.api.nvim_buf_set_var(buf_id, 'kznllm', true)`
and then query for this variable on invoke_llm to see if it's a plugin file, this way we don't need to manage a global variable at all.

```
  local buf = vim.api.nvim_win_get_buf(0)
  local buf_is_scratch, buf_data = pcall(vim.api.nvim_buf_get_var, buf, 'kznllm')
```

**Comment by chottolabs** [comment]
> What about creating the buffer with a variable, like, `vim.api.nvim_buf_set_var(buf_id, 'kznllm', true)`

hmm, didn't know about this feature but I like the sound of that

> `vim.bo[buf].bufhidden = 'wipe'`

didn't know about this either, i think this was actually what i was looking for originally to "invalidate" the buffer and check with `api.nvim_buf_is_valid` - but no global variable sounds better

**Comment by chottolabs** [comment]
wrote up something for the sake of learning how it works - i can push it into this if it makes sense

```diff
diff --git a/lua/kznllm/presets.lua b/lua/kznllm/presets.lua
index 6ffdb55..49113f7 100644
--- a/lua/kznllm/presets.lua
+++ b/lua/kznllm/presets.lua
@@ -10,13 +10,6 @@ local M = {}
 
 --TODO: PROMPT_ARGS_STATE is just a bad persistence layer at the moment, I don't really want to write files everywhere...
 
--- ORIGIN refers to the buffer where the user invoked the plugin.
--- SCRATCH is a temporary buffer for debugging/chat.
-M.BUFFER_STATE = {
-  SCRATCH = nil,
-  ORIGIN = nil,
-}
-
 M.PROMPT_ARGS_STATE = {
   current_buffer_path = nil,
   current_buffer_context = nil,
@@ -194,8 +187,6 @@ function M.invoke_llm(make_data_fn, make_curl_args_fn, make_job_fn, opts)
 
   local active_job
 
-  M.BUFFER_STATE.ORIGIN = api.nvim_win_get_buf(0)
-
   kznllm.get_user_input(function(input)
     M.PROMPT_ARGS_STATE.user_query = input
     M.PROMPT_ARGS_STATE.replace = not (api.nvim_get_mode().mode == 'n')
@@ -209,9 +200,10 @@ function M.invoke_llm(make_data_fn, make_curl_args_fn, make_job_fn, opts)
     end
 
     -- don't update current context if scratch buffer is open
-    if not M.BUFFER_STATE.SCRATCH then
+
+    if not vim.b.debug then
       -- similar to rendering a template, but we want to get the context of the file without relying on the changes being saved
-      local buf_filetype, buf_path, buf_context = kznllm.get_buffer_context(M.BUFFER_STATE.ORIGIN, opts)
+      local buf_filetype, buf_path, buf_context = kznllm.get_buffer_context(0, opts)
       M.PROMPT_ARGS_STATE.current_buffer_filetype = buf_filetype
       M.PROMPT_ARGS_STATE.current_buffer_path = buf_path
       M.PROMPT_ARGS_STATE.current_buffer_context = buf_context
@@ -224,28 +216,14 @@ function M.invoke_llm(make_data_fn, make_curl_args_fn, make_job_fn, opts)
 
     -- open up scratch buffer before setting extmark
     if opts and opts.debug and opts.debug_fn then
-      if M.BUFFER_STATE.SCRATCH then
-        api.nvim_buf_delete(M.BUFFER_STATE.SCRATCH, { force = true })
-        M.BUFFER_STATE.SCRATCH = nil
-      end
-      M.BUFFER_STATE.SCRATCH = kznllm.make_scratch_buffer()
-
-      -- Set up key mapping to close the buffer
-      api.nvim_buf_set_keymap(M.BUFFER_STATE.SCRATCH, 'n', '<leader>q', '', {
-        noremap = true,
-        silent = true,
-        callback = function()
-          api.nvim_exec_autocmds('User', { pattern = 'LLM_Escape' })
-          api.nvim_buf_delete(M.BUFFER_STATE.SCRATCH, { force = true })
-          M.BUFFER_STATE.SCRATCH = nil
-        end,
-      })
-
-      stream_end_extmark_id = api.nvim_buf_set_extmark(M.BUFFER_STATE.SCRATCH, M.NS_ID, 0, 0, {})
+      local buf_id = kznllm.make_scratch_buffer()
+      api.nvim_buf_set_var(buf_id, 'debug', true)
+
+      stream_end_extmark_id = api.nvim_buf_set_extmark(0, M.NS_ID, 0, 0, {})
       opts.debug_fn(data, M.NS_ID, stream_end_extmark_id, opts)
     else
       local _, crow, ccol = unpack(vim.fn.getpos '.')
-      stream_end_extmark_id = api.nvim_buf_set_extmark(M.BUFFER_STATE.ORIGIN, M.NS_ID, crow - 1, ccol - 1, { strict = false })
+      stream_end_extmark_id = api.nvim_buf_set_extmark(0, M.NS_ID, crow - 1, ccol - 1, { strict = false })
     end
 
     local args = make_curl_args_fn(data, opts)
```

**Comment by dceluis** [comment]
Nice! I really like the vim.b.debug shorthand because is doesnt raise anything if the variable is not set, just evaluates to false.

I think
` stream_end_extmark_id = api.nvim_buf_set_extmark(0, M.NS_ID, 0, 0, {}) `
should be
` stream_end_extmark_id = api.nvim_buf_set_extmark(buf_id, M.NS_ID, 0, 0, {}) `

**Comment by dceluis** [comment]
Also, i think we could still store a reference to the originally open buffer, but it doesn't need to be a global variable.

something like
local original_buf = api.nvim_win_get_buf(0)
instead of 
M.BUFFER_STATE.ORIGIN = api.nvim_win_get_buf(0)

this way we don't rely on passing 0 everywhere, which _may_ introduce some errors in the future as the plugin grows.

**Comment by chottolabs** [comment]
@dceluis 🤔 i think it's good now, lmk if you notice anything whenever you find the time

**Comment by dceluis** [comment]
Thanks for the additions. I added a minor fix, I think this is ready too.

**Pull request merged**
